# Generated by Django 3.2.22 on 2023-10-29 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_purchaseddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseddetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
